### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [maposmatic/maposmatic#8]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project [seems to be using osmosis](https://github.com/maposmatic/maposmatic/search?q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+osmosis), which [will not follow redirects by default](https://trac.openstreetmap.org/ticket/5483).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https? All services respond over https and will start redirecting soon.

**Comment by mpetazzoni** [comment]
Thanks for the report.

Nothing in MapOSMatic hits up planet.openstreetmap.org directly at runtime. It's only for the minutely updates of the database (managed by https://github.com/maposmatic/ocitysmap/blob/master/support/planet-update.sh, which ultimately delegates to Osmosis as you mentioned), and that's easily set in configuration for whoever sets up the database update pipeline.

I don't think anything in the source code of MapOSMatic needs to be updated to address this directly.
